## StatefulSet definition
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cdb  # cdb = chordial database
  namespace: chordial-ns
  labels:
    app: chordial
spec:
  serviceName: chordial
  replicas: 1
  selector:
    matchLabels:
      app: chordial
  volumeClaimTemplates:
  - metadata:
      name: chordial-volume-claim
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Mi
#      storageClassName: chordial-storage
  template:

    ## Pod definition
    metadata:
      name: chordial-pod
      namespace: chordial-ns
      labels:
        app: chordial
    spec:
      containers:
      - name: chordial-container
        image: chordial/server:1.2.5
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "500Mi"
          requests:
            memory: "300Mi"
        env:
        - name: SEED_HOSTNAME
          value: "cdb-0.chordial.chordial-ns.svc.cluster.local"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - name: service
          containerPort: 8080
        - name: membership
          containerPort: 22200
        - name: partitioning
          containerPort: 22201
        - name: replication
          containerPort: 22202
        volumeMounts:
        - name: chordial-volume-claim
          mountPath: /var/lib/chordial
        readinessProbe:
          exec:
            command:
            - chordial
            - ready
          initialDelaySeconds: 30
          periodSeconds: 15

---

## StorageClass definition
#kind: StorageClass
#apiVersion: storage.k8s.io/v1
#metadata:
#  name: chordial-storage
#provisioner: kubernetes.io/no-provisioner
#volumeBindingMode: WaitForFirstConsumer

