apiVersion: v1
kind: Pod
metadata:
  name: chordial-pod
  namespace: chordial-ns
  labels:
    appName: chordial
spec:
  containers:
    - name: chordial-container
      image: chordial/server
      resources:
        limits:
          memory: "500Mi"
        requests:
          memory: "300Mi"
      env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

