## External Service definition
apiVersion: apps/v1
kind: Service
metadata:
  name: nodedial
  namespace: nodedial-ns
  labels:
    app: nodedial
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: nodedial
