## Headless Service definition
apiVersion: v1
kind: Service
metadata:
  name: nhs  # nhs = nodedial headless service
  namespace: nodedial-ns
  labels:
    app: nodedial
spec:
  clusterIP: None
  ports:
    - name: membership
      port: 22200
    - name: failure-det
      port: 22201
    - name: partitioning
      port: 22202
    - name: replication
      port: 22203
  selector:
    app: nodedial

