## StatefulSet definition
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ndb  # ndb = nodedial database
  namespace: nodedial-ns
  labels:
    app: nodedial
spec:
  serviceName: nhs
  replicas: 1
  selector:
    matchLabels:
      app: nodedial
  volumeClaimTemplates:
  - metadata:
      name: nodedial-volume-claim
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Mi
#      storageClassName: nodedial-storage
  template:

    ## Pod definition
    metadata:
      name: nodedial-pod
      namespace: nodedial-ns
      labels:
        app: nodedial
    spec:
      containers:
      - name: nodedial-container
        image: nodedial:1.0.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "500Mi"
          requests:
            memory: "300Mi"
        env:
        - name: SEED_HOSTNAME
          value: "ndb-0.nhs.nodedial-ns.svc.cluster.local"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - name: service
          containerPort: 8080
        - name: membership
          containerPort: 22200
        - name: failure-det
          containerPort: 22201
        - name: partitioning
          containerPort: 22202
        - name: replication
          containerPort: 22203
        volumeMounts:
        - name: nodedial-volume-claim
          mountPath: /var/lib/nodedial
        readinessProbe:
          exec:
            command:
            - nodedial
            - ready
          initialDelaySeconds: 20
          periodSeconds: 12

---

## StorageClass definition
#kind: StorageClass
#apiVersion: storage.k8s.io/v1
#metadata:
#  name: nodedial-storage
#provisioner: kubernetes.io/no-provisioner
#volumeBindingMode: WaitForFirstConsumer

